//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_UserInRole
    {
        public System.Guid App_UserInRole_ID { get; set; }
        public System.Guid App_User_ID { get; set; }
        public System.Guid App_Role_ID { get; set; }
    }
}
