//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRCodePackage
    {
        public int QRCodePackage_ID { get; set; }
        public Nullable<int> QRCodePackageType_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> ProductBrand_ID { get; set; }
        public Nullable<int> Factory_ID { get; set; }
        public Nullable<int> Batch_ID { get; set; }
        public Nullable<int> ProductLabel_ID { get; set; }
        public string Name { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string ProfileQRCode { get; set; }
        public Nullable<bool> SoundEnable { get; set; }
        public Nullable<bool> SMS { get; set; }
        public string Prefix { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> QRCodeStatus_ID { get; set; }
        public Nullable<int> QRCodeProductStatus_ID { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> SellCount { get; set; }
        public Nullable<int> QRCodeNumber { get; set; }
        public Nullable<int> QRCodeUsed { get; set; }
        public Nullable<int> QRCodeCancel { get; set; }
        public Nullable<int> QRCodeAvailable { get; set; }
        public string SerialNumberStart { get; set; }
        public string SerialNumberEnd { get; set; }
        public string SerialNumberText { get; set; }
        public string SerialNumberCancelText { get; set; }
        public Nullable<System.Guid> ManageBy { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.Guid> AgencyAssign { get; set; }
        public string ManufactureShift { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string WarrantySerial { get; set; }
        public Nullable<int> WarrantyMonth { get; set; }
        public Nullable<System.DateTime> WarrantyStartDate { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
        public string UsedName { get; set; }
        public string UsedAddress { get; set; }
        public string UsedPhone { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<bool> PendingActive { get; set; }
        public Nullable<System.DateTime> PendingActiveDate { get; set; }
        public string ProduceInfoStaff { get; set; }
        public string ProduceInfo { get; set; }
        public Nullable<bool> ProduceInfoDisplay { get; set; }
        public Nullable<System.DateTime> ProduceInfoEditDate { get; set; }
        public string QualityInfo { get; set; }
        public Nullable<bool> QualityInfoDisplay { get; set; }
        public Nullable<System.DateTime> QualityInfoEditDate { get; set; }
        public string DeliveryInfo { get; set; }
        public Nullable<System.DateTime> DeliveryInfoEditDate { get; set; }
        public string StoreInfo { get; set; }
        public Nullable<bool> StoreInfoDisplay { get; set; }
        public Nullable<System.DateTime> StoreInfoEditDate { get; set; }
        public Nullable<int> Warehouse_ID { get; set; }
        public string CustomerInfo { get; set; }
        public Nullable<System.Guid> CheckApproveBy { get; set; }
        public Nullable<System.DateTime> CheckApproveDate { get; set; }
        public Nullable<System.Guid> AdminApproveBy { get; set; }
        public Nullable<System.DateTime> AdminApproveDate { get; set; }
        public Nullable<int> QRQueue { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<System.Guid> AssignEmp { get; set; }
        public string SerialNumberStartExpected { get; set; }
        public string SerialNumberEndExpected { get; set; }
        public string SerialNumberTextExpected { get; set; }
        public Nullable<int> PalletNum { get; set; }
    }
}
